---
all:
  hosts:
    # sqlred:
    #   internal_ip: 192.168.100.55
    #   internal_gateway: 192.168.100.1
    sqlbuntu:
      internal_ip: 192.168.100.54
      internal_gateway: 192.168.100.1

  ansible_user: ansible
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=30'

# export ANSIBLE_FORCE_COLOR=1 
# ansible-playbook -i hosts.yml site.yml --vault-password-file=../vault-pass --skip-tags network 2>&1 | tee logs/playbook-run-log.txt
# ansible-playbook -i hosts.yml site.yml --vault-password-file=../vault-pass --tags network 2>&1 | tee logs/playbook-run-log.txt
